### ISSUE TITLE
Proxy rotation

### ISSUE THREAD

**Issue by clarkk** [gsouf/google-url#14]
I'm trying to setup proxy rotation but get an error

Docs:
https://github.com/gsouf/google-url/blob/master/doc/proxy_rotation.md

Code
```
$defaultDelays = [
	-1 => [0, 60]
];
$proxyPool = new \GoogleUrl\ProxyPool($defaultDelays);
$proxy1 = new \GoogleUrl\Proxy\ProxyObject('host', 8888, 0, 0, 0, false);
```

Error
```
PHP Warning:  Missing argument 7 for GoogleUrl\Proxy\ProxyObject::__construct(), called in /var/Cronjob_check_serp_position.php on line 15 and defined in /var/google-url/lib/GoogleUrl/Proxy/ProxyObject.php on line 39
```

**Comment by gsouf** [comment]
Indeed the doc is wrong.

Please  try the following : 
$proxy1 = new \GoogleUrl\Proxy\ProxyObject('host', 8888, null, null, 0, 0, 0, false);

The proxy rotation will be subject to a refactoring, it is not instintive enough.
Thanks for repporting !
