### ISSUE TITLE
Search results 0

### ISSUE THREAD

**Issue by clarkk** [gsouf/google-url#15]
The script has worked fine until yesterday..

Now the script returns 0 results..

How to debug the script? Maybe Google has detected the scraping

**Comment by clarkk** [comment]
- or maybe google has changed the data structure?

**Comment by clarkk** [comment]
Have tried the script from 3-4 different IP adresses and all returns `0`

```
$positions = $page->getPositions();
```

**Comment by LiloBzH** [comment]
same thing here.

No result

**Comment by gsouf** [comment]
Ok, let me check very soon

**Comment by gsouf** [comment]
Ok, google replaced <li> with <div> in its DOM. It should be ok for now. Please let me know it some errors still happen, I dont have much time to test now because of summertime.

Thanks

**Comment by LiloBzH** [comment]
it's seems ok for me

Thanks

**Comment by radolfi** [comment]
In my tests there are local listings in the natural listings now.
I tried to rewrite const NATURAL_QUERY to exclude li[@id = 'lclbox'] but I failed.

My test query: "cafe berlin"

-> natural listings on page 1 (15 are 5 too much):
  1: http://www.berlin.de/cafes/
  2: http://www.berlin.de/cafes/stadtteile/
  3: http://www.berlin.de/bars/adressen/bar/cafe-commune-0d1ab041fbae2cc0a7f4503ae944708a.html
  4: http://www.schwarzescafe-berlin.de/
  5: https://plus.google.com/110132661049009362940/about?hl=de&socfid=web:lu:unknown:localgroupedresult&socpid=1
  6: http://www.cafeeinstein.com/
  7: http://www.einsteinudl.com/
  8: http://www.literaturhaus-berlin.de/
  9: http://www.oliv-cafe.de/
  10: http://www.cafe-butter.de/
  11: http://www.cremeguides.com/de/berlin-kategorien/food-in-berlin/cafes-kuchen-kaffee-in-berlin/
  12: http://www.top10berlin.de/de/cat/essen-267/cafes-fuer-kaffeeliebhaber-567
  13: http://www.yelp.de/c/berlin/cafe
  14: http://www.visitberlin.de/de/erleben/essen-trinken/cafes
  15: http://www.cafe-k.com/

**Comment by radolfi** [comment]
Is there is already a solution?
