### ISSUE TITLE
Fatal error: Uncaught exception 'GoogleUrl\Exception\CurlException

### ISSUE THREAD

**Issue by m1chae11** [gsouf/google-url#19]
Hi there,
I have setup a simple proxy (list from hidemyass), I tried many different proxies "http/https',
every time i receive this error:

<pre>
Fatal error: Uncaught exception 'GoogleUrl\Exception\CurlException' with message 'HTTP query failled [curl-error : 56 - Received HTTP code 502 from proxy after CONNECT ] for the following URL : https://www.google.com/search?q=agata&start=0&num=20&complete=0&pws=0&hl=en&lr=lang_en' in /home4/works/public_html/myurl.com/google-url/lib/GoogleUrl.php:356 Stack trace: #0 /home4/works/public_html/myurl.com/google-url/google-search.php(19): GoogleUrl->search('adam', Object(GoogleUrl\SimpleProxy)) #1 {main} thrown in /home4/mworks/public_html/myurl.com/google-url/lib/GoogleUrl.php on line 356
</pre>
I receive different [curl- error] , when i change to different proxy sometimes..

<b>My execution code is:</b>
<pre>
        include __DIR__ . "/autoload.php";
        use GoogleUrl\SimpleProxy;
        $proxy2 = new \GoogleUrl\SimpleProxy("202.108.35.151", "80");
        $googleUrl= new \GoogleUrl();      
        $googleUrl->setLang('en'); 
        $googleUrl->setNumberResults(20);
        $simpsonPage1=$googleUrl->setPage(0)->search("agata",$proxy2); 
</pre>

I tried catching the error with:
<pre>
try{
$googleUrl= new \GoogleUrl();   
}catch( GoogleUrl\Exception\CaptachaException $ex){
 
    echo $ex->getMessage();

}
</pre>
... but i  get no results

<b>I figured that the error hangs in GoogleUrl.php at:</b>
<pre>
 $r=$c->exec();
        
        if(false === $r){
</pre>

Can someone help, much appreciated!

Thanks
Mike

**Comment by gsouf** [comment]
Hi @m1chae11 

Your error is pretty similar with #16 that's seems to be an error with the proxy itself. That's very common when you use a public proxy. I recommend not to use a public proxy.


I get the same error when I try to run the command from terminal:

```
$ curl --proxy 202.108.35.151:80 https://github.com
curl: (56) Received HTTP code 502 from proxy after CONNECT
```

To catch the error you have to use the good exception: 

```php

try {
    $googleUrl = new \GoogleUrl();   
} catch ( GoogleUrl\Exception\CurlException $ex) {
 
    // An error happened at the CURL level (bad proxy, bad address.....

} catch (GoogleUrl\Exception\CaptachaException $ex) {
 
    // You are blocked by google's captcha

}
```
