### ISSUE TITLE
Natural results empty

### ISSUE THREAD

**Issue by alinr** [gsouf/google-url#20]
Even though ["textContent"] is not empty, no natural results are shown. In ["textContent"] the html markup for the searchresults is not available. Looks like:

"SuchergebnisseDie Simpsons â Wikipediahttps://de.wikipedia.org/wiki/Die_SimpsonsIm CacheDie Simpsons ist eine von Matt Groening geschaffene, vielfach ausgezeichnete US-amerikanische Zeichentrickserie des Senders Fox. Sie ist die am lÃ¤ngsten ...âDie Simpsons/Episodenliste - âFiguren aus Die Simpsons - âMatt Groening - âDer FilmDie Simpsons: Alle Infos, Videos und Bilder zur Kult-Serie.www.prosieben.de › TVIm CacheÃhnliche SeitenDie Simpsons - alles rund um die gelbe Familie aus Springfield mit Oberhaupt Homer Simpson und Sohn Bart.Die Simpsons die gelbe Zeichentrick Familie aus Springfield ...www.die-simpsons.de/Im CacheÃhnliche SeitenThe Simpsons Online berichtet Ã¼ber aktuelles von den Simpsons rund um Homer, Marge, Bart, Lisa und Maggie Simpson.SIMPSON STRONG-TIEÂ® - Ihr professioneller Partner fÃ¼r ...www.strongtie.de/Im CacheÃhnliche SeitenDiese Seite Ã¼bersetzenSimpson Strong-TieÂ® fÃ¼hrt ist WeltmarktfÃ¼hrer im Bereich Holzverbinder. Zu unserem Sortiment gehÃ¶ren z.B. Balkenschuhe, Winkelverbinder, ...Die Simpsons bei fernsehserien.dewww.fernsehserien.de/die-simpsonsIm CacheÃhnliche SeitenâDie Simpsonsâ sind eine amerikanische Durchschnittsfamilie. Immer neue Geschichten gibt es Ã¼ber Homer, Marge, Bart, Lisa und Maggie und Ã¼ber die ...Simpsonspediasimpsonspedia.net/Im CacheÃhnliche SeitenâThe Simpsonsâ bzw. im Deutschen âDie Simpsonsâ ist mehr als nur eine Zeichentrickserie. Die Simpsonspedia wurde ins Leben gerufen, um Wissenswertes ...Die Simpsons: GerÃ¼chte um Serien-Aus - TV - Bild.dewww.bild.de › Unterhaltung › TV › Die Simpsons30.09.2015 - Wenn es nach dem Serien-Produktionsmitarbeiter Al Jean geht, ist mit den Simpsons bald Schluss!The Simpsons | Serie bei Serienjunkies.dewww.serienjunkies.de › SerienIm CacheÃhnliche Seiten Bewertung: 4,5 - â1.234 AbstimmungsergebnisseDie animierte Serie âThe Simpsonsâ erzÃ¤hlt die Abenteuer der gleichnamige gelben Familie, die in der fiktiven Stadt Springfield lebt. Ihre Mitglieder sind: Homer ...Sideshow Bob schlÃ¤gt zu: Schock! Dieses "Simpsons" - Focuswww.focus.de/.../sideshow-bob-schlaegt-zu-schock-dieses-simpsons-familie... Bewertung: 3,4 - â5 AbstimmungsergebnisseShowdown in Springfield: Die 27. Staffel der Kult-Serie âSimpsonsâ wirft bereits ihre Schatten voraus. Nun gibt es die erste groÃe EnthÃ¼llung. Eine ewige ...The Simpsons : Synchronsprecher Norbert Gastell ... - Focuswww.focus.de › Kultur › Kino & TV30.11.2015 - Nein!â, âMmmh...â oder auch âJuchuuu!â: Homer Simpson drÃ¼ckt sich auf eine sehr eigene, charakteristische Weise aus. Seine Stimme gehÃ¶rt ..."

Adwords results works well.

**Comment by gsouf** [comment]
@alinr I ant reproduce your issue. an you give me ore details about what you are doing ?

**Comment by alinr** [comment]
I followed the example code in your readme file. Tried de, en, fr as languages and different keywords. Always the same (no) result. 

I now use dev-v2, which works well. Faced one problem with captcha. Here: https://github.com/gsouf/google-url/blob/dev-v2/src/GoogleUrl/Captcha/CaptchaPage.php

use GoogleUrl\CaptchaSolver\CaptchaImage;
should be
use GoogleUrl\Captcha\Solver\CliSolver;

**Comment by gsouf** [comment]
@alinr V2 is not ready it can be inconsistent atm

**Comment by gsouf** [comment]
The version 1 works fine for me with the following code: 

```

<?php
include __DIR__ . "/vendor/autoload.php";

$googleUrl=new \GoogleUrl();
$googleUrl->setLang('de') // lang allows to adapt the query (tld, and google local params)
    ->setNumberResults(10);                        // 10 results per page
$acdcPage1=$googleUrl->setPage(0)->search("acdc"); // acdc results page 1 (results 1-10)
$acdcPage2=$googleUrl->setPage(1)->search("acdc"); // acdc results page 2 (results 11-20)

$googleUrl->setNumberResults(20);
$simpsonPage1=$googleUrl->setPage(0)->search("simpson"); // simpsons results page 1 (results 1-20)


$positions=$simpsonPage1->getPositions();

echo "results for " . $simpsonPage1->getKeywords() . PHP_EOL;

foreach($positions as $result){

    echo $result->getPosition() . ". " . $result->getWebsite();
    echo PHP_EOL;

}
```

Getting the following output: 

```
results for simpson
1. de.wikipedia.org
2. www.prosieben.de
3. www.die-simpsons.de
4. www.strongtie.de
5. www.fernsehserien.de
6. simpsonspedia.net
7. www.tagesspiegel.de
8. www.serienjunkies.de
9. www.bild.de
10. www.computerbild.de
11. www.focus.de
12. www.focus.de
13. www.n-tv.de
14. shop.lego.com
15. de.simpsons.wikia.com
16. de.simpsons.wikia.com
17. simpsons.1001spiele.de
18. www.nerdcore.de
19. www.simpsonsnews.de
20. www.amazon.de
```

**Comment by gsouf** [comment]
I'm closing the issue. If you need additional support feel free to open it again
