### ISSUE TITLE
Issues with Xpath patterns

### ISSUE THREAD

**Issue by sameerpanjwani** [gsouf/google-url#21]
Just trying your v2 script, I think there are a few issues:

1) adwordsUrl and title for ad is always coming blank
2) The news results are not being scraped, always empty array

**Comment by gsouf** [comment]
@sameerpanjwani  Thanks for reporting

That's possible because v2 is not finished yet. I should tell it in the readme. By the way I keep your issue opened until I fix it !

**Comment by gsouf** [comment]
Closing the issue because it is replaced by https://github.com/serp-spider/search-engine-google ;)
