### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by sameerpanjwani** [gsouf/google-url#22]
Can you possibly add the feature to:

1) detect whether result a local result or regular result

2) in a sample search like this: `https://www.google.com/search?lr=lang_en&hl=en&q=restaurants+in+new+york&complete=0&pws=0` can you detect whether `mapEnabled:yes/no` and show the `localPackResults` even though no urls are available but would be useful to get the local headings and to adjust the ranking position of the no.1 site to no.4 after accounting for the 3 local pack results.

**Comment by gsouf** [comment]
That looks to be a good enhancement.

Can you please tell me more about the ``mapEnabled`` feature, I couldnt find much about it.

**Comment by sameerpanjwani** [comment]
Basically if you search for restaurants or any local query, Google
sometimes will show a map in their results and mapEnabled will basically
say if map was shown or not.

**Comment by gsouf** [comment]
``mapEnabled`` would be a property available on the search result returned by the library ?

**Comment by sameerpanjwani** [comment]
Yeah basically for example if the XPath selector: `//*[@id="lu_map"]`  returned a result, then `mapEnabled` could be `yes`

**Comment by gsouf** [comment]
Got it. I will add that soon enough

**Comment by Human018** [comment]
I second this. It would be great to see which position a domain appears within the maps listings and then within the standard organic listings. Would this be a hard feature to implement?

**Comment by gsouf** [comment]
Should not be difficult, I take this in consideration

**Comment by gsouf** [comment]
I'm closing the issue because it will be available in https://github.com/serp-spider/search-engine-google
