### ISSUE TITLE
Anyway to store the raw HTML somewhere?

### ISSUE THREAD

**Issue by sameerpanjwani** [gsouf/google-url#23]
Hi is there anyway I could store the raw html of the scraped Google page in my aws s3 bucket or in my local filesystem? Do you have a function that will return the raw html of the page?

**Comment by gsouf** [comment]
Yes that's actually very simple because the search API returns an [DOCDocument instance](http://php.net/manual/fr/class.domdocument.php) and you can use the native ``saveHtml`` method to get it:

```php
   $results = $googleUrl->search(...);
   $html = $results->saveHtml();
```

Optionally you can save it in a file: 


```
   $results = $googleUrl->search(...);
   $results->saveHtmlFile("filename.html");
```

**Comment by sameerpanjwani** [comment]
Great, thanks!
