### ISSUE TITLE
v1 - local search issue

### ISSUE THREAD

**Issue by sameerpanjwani** [gsouf/google-url#24]
For some parameters like `uule` that we need to pass to Google for search, they should not be urlencoded because then the value is lost. Since you're using `http_build_query` for your parameters, this particular parameter's value is being converted wrongly.

Example:
` $googleUrl->setLang('en')->setNumberResults(10)->setTld("co.in")->setParam("uule","w+CAIQICIJTmV3IERlbGhp"); `

Ideally it should call
`https://www.google.co.in/search?lr=lang_en&hl=en&q=chinese+restaurants&complete=0&pws=0&uule=w+CAIQICIJTmV3IERlbGhp` but it converts the "+" sign and that results in a wrong search in Google. So perhaps you need a function called, `setRawParam` which is then appended in it's raw form at the end of the built query.

**Comment by gsouf** [comment]
I see the problem.

``setRawParam`` looks to be good solution, though I have to use the proper solution to implement it.

I the interim you can replace you ``setParam`` call with:

```php
->setParam("uule",urldecode("w+CAIQICIJTmV3IERlbGhp"));
```

I didnt give it a try but that should work.

**Comment by gsouf** [comment]
``setRawParam`` was implemented
