### ISSUE TITLE
Results are empty : $result->getNaturals() return empty.

### ISSUE THREAD

**Issue by kaushikkavi** [gsouf/google-url#30]
Hello,

I have issue google result results are empty and adWord works fine. Can you tell me where is wrong . It works fine yesterday but suddenly it stop working today.

$result->getNaturals() // return empty object
$result->getAdword() // is working fine

I have natural query like NATURAL_QUERY="//div[@id = 'ires']/ol/descendant::*[self::div or self::li][@class='g']";

i download latest repo but still not working.

Plz suggest.

**Comment by gsouf** [comment]
Hi,

Indeed there is an update on the google side. I pushed a fix, can you tell me if it's better ?

**Comment by kaushikkavi** [comment]
Hello,

Yes not it works. i check GoolgeDom.php and update file. It now works fine.

Thanks for fixing.
