### ISSUE TITLE
charset problem

### ISSUE THREAD

**Issue by JD719** [gsouf/google-url#31]
Hey, congratulations for this amazing work.

My problem is when the output generated by getTitle() has ISO 8859-1 characters, they come wrongly represented.

In example:
- ú is printed as ÃƒÂº
- ñ is printed as ÃƒÂ±

I think that's utf8_encode() representation of those characters, however utf8_decode() is not reverting them.

Any idea what is going wrong?

**Comment by gsouf** [comment]
It's hard to deal with encoding in this case because it depends on many things. What happens if you set the param ``oe`` to ``utf-8``: ``$url->setParam('oe', 'utf-8');

**Comment by JD719** [comment]
setParam('oe', 'iso-8859-1') did it!
Thanks a lot!

**Comment by gsouf** [comment]
Good :) 
``oe`` means "output encoding". If everything is ok I'm closing the issue
