### ISSUE TITLE
Xpath patterns

### ISSUE THREAD

**Issue by pamenary** [gsouf/google-url#33]
const NATURAL_QUERY="//div[@id = 'ires']/descendant::*[self::div or self::li][@class='g']";

**Comment by gsouf** [comment]
Can you elaborate please?

**Comment by valentin-** [comment]
The script stopped working for me. It just returned adwords results (tested with your simpson demo). I changed the const like pamenary mentioned, now it's working again.

**Comment by gsouf** [comment]
PR then, that's what github is made for...
