### ISSUE TITLE
  Manual Captcha resolver

### ISSUE THREAD

**Issue by gsouf** [gsouf/google-url#4]
When captcha is met
=> get the picture and allow to save it
=> allow to show it and create a response request to solve it

**Comment by SneakyBobito** [comment]
Instead of static resolver the best owuld be to make a catcharesolver adapter, that owuld allow to implement : 

- manual resolver
- services like http://www.deathbycaptcha.com/

**Comment by SneakyBobito** [comment]
Captcha solver implemented, should implement deathbycaptcha now

**Comment by MarcoG3** [comment]
Any update con captcha solver?

**Comment by gsouf** [comment]
It's on the way on the V2

**Comment by cicaglisa** [comment]
Still waiting and hoping on the manual captcha feature.. Any news?

**Comment by gsouf** [comment]
Some improvement lately for the version 2. However nothing final yet

**Comment by MarcoG3** [comment]
I recommend you using DeathByCaptcha automatic resolver. To make it as general as possible an idea would be letting the user decide what is the captcha POST param to send back to server, as well as with the URL

**Comment by gsouf** [comment]
@MarcoG3 deathbycaptcha is on the way too, that will be a common interface

**Comment by MarcoG3** [comment]
If you need help on anything I'll be happy to contribute. Are you working on dev-v2 branch, currently?

**Comment by gsouf** [comment]
Actually I'm working on something more general based on the work made on the dev-v2 branch. That will be more general because it will not be focused on google, but any search engine will be possible.

**Comment by MarcoG3** [comment]
Looks great. Looking forward to see v2 as soon as it is ready.

**Comment by cicaglisa** [comment]
DeathByCaptcha is commercial and such approach is also already implemented in bunch of software. So, I think manual entry of captcha is more suitable as it's free, plus it's not yet implemented in any open source google parser..

**Comment by MarcoG3** [comment]
Manual entry of captcha is not really that useful. The main use of Google URL is to automatically scrape results from Google search engine. There is no point in running an automate software and periodically inputting captcha, if needed.

**Comment by gsouf** [comment]
There is no universal solution, sometimes you want something manual, sometimes you want to implement some commercial service (e.g deathbycaptcha). That's why the library will offer an interface that allow any implementation

**Comment by hughsaffar** [comment]
Just wondering is there a news about this feature? I tried to resolve the Captcha. I am at the level that I can send the image to the third party manual resolver to get the Captcha code, but when I submit it, I redirect back to the same page!

**Comment by gsouf** [comment]
Please wait for the next version, should come by the end of January

**Comment by hughsaffar** [comment]
That would be awesome!!

**Comment by MarcoG3** [comment]
Any progress on automatic captcha solver?

**Comment by hughsaffar** [comment]
+1

**Comment by gsouf** [comment]
Due to additional major refactoring there is more delay than I announced but that's definitively on the way for the V2!

**Comment by JD719** [comment]
I can't wait!

**Comment by gsouf** [comment]
I close the issue because this subject is on the roadmap of https://github.com/serp-spider/search-engine-google
