### ISSUE TITLE
GeoLocation

### ISSUE THREAD

**Issue by urza1234** [gsouf/google-url#8]
Your project here is pretty cool, there's a google parameter I'm using that you might want to know about:

You can instruct google to execute searches as if you were submitting the search from a location of your choice, it is a functionality they use to create localized results in the Adwords iframe, this is info useful for advertisers and local business. The param to add to your googleParams array is "uule", and the location value is "w+CAIQICI" . "(base64 encoded string)"

This localization tool could especially help users take advantage of your proxy rotation feature without having their results skewed by proxy location.

I thought you might think this info is worth adding to your tool, more background can be found here: http://moz.com/ugc/geolocation-the-ultimate-tip-to-emulate-local-search

**Comment by SneakyBobito** [comment]
Hello,

This feature is indeed very interesting. I will implement it in the library.
I didnt have the time to read all about it for the moment.

In the interim you can still use it by yourself ! Actually i'm just figuring out that i forgot to document it, but you can add some params by yourself on this simple way :

```php
$googleUrl->setParam("paramName", "paramValue");
// you can check if a param is already set :
$googleUrl->hasParam("paramName");
// get the value of the param
$paramValue  = $googleUrl->param("paramName");
// remove a param
$googleUrl->setParam("paramName", null);
```

In your case it would be

```php
$googleUrl->setParam("uule", "w+CAIQICI");
```

Stay tuned for the implementation !

**Comment by urza1234** [comment]
Thanks, I've just added it to the library myself with its own method. I just thought you might think it was cool and useful.
